import os
import sys
import json
import uuid
import asyncio
import shutil
from pathlib import Path
from typing import Dict, Any, AsyncGenerator

# Ensure project root is importable
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi import FastAPI, UploadFile, File, Form, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

from reproagent.environment import ReproAgentEnv
from reproagent.models import LLMClient
from utils.pdf_reader import extract_text
from agents.reasoning_agent import create_agent
from reproagent.state import PaperState

app = FastAPI(title="ReproAgent API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, restrict to frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Store active medium-mode tasks (in-memory for simplicity)
ACTIVE_TASKS: Dict[str, Dict[str, Any]] = {}

@app.get("/api/health")
def health_check():
    return {"status": "ok"}

# Serve static files for Hugging Face Spaces
frontend_dist = Path(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend", "dist"))
if frontend_dist.exists():
    app.mount("/assets", StaticFiles(directory=frontend_dist / "assets"), name="assets")
    @app.get("/{full_path:path}")
    async def catch_all(full_path: str):
        if full_path.startswith("api/"):
            raise HTTPException(status_code=404, detail="Not Found")
        return FileResponse(frontend_dist / "index.html")

@app.post("/api/easy-mode")
async def easy_mode(file: UploadFile = File(...)):
    """Extract text from PDF, summarize into bullet points using LLM, and generate PPT."""
    # 1. Save uploaded file
    tmp_dir = Path("data/tmp")
    tmp_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = tmp_dir / f"{uuid.uuid4()}.pdf"
    
    try:
        with open(pdf_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        
        # 2. Extract text
        text = extract_text(str(pdf_path))
        if not text:
            raise HTTPException(status_code=400, detail="Could not extract text from PDF")
        
        # 3. Use LLM to extract bullet points
        llm = LLMClient()
        prompt = f"""Analyze this machine learning research paper and extract the following information for a presentation:
1. A catchy title for the presentation.
2. A professional 3-4 sentence description/summary of the paper.
3. 5-7 concise bullet points highlight key contributions, methodology, and results.

Return ONLY a JSON object with keys: "title", "description", and "bullets" (array of strings).

Paper text (first 6000 chars):
{text[:6000]}"""
        
        response = llm.generate_structured(prompt)
        
        paper_title = response.get("title", "Research Paper Summary")
        paper_desc = response.get("description", "Failed to generate a description.")
        bullets = response.get("bullets", ["No highlights found."])
        
        if not isinstance(bullets, list):
            bullets = [str(bullets)]
            
        # 4. Generate PPT
        prs = Presentation()
        
        # 1. Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        
        # Add some color to the background (Rectangles are used as backgrounds in python-pptx)
        left = top = 0
        width = prs.slide_width
        height = prs.slide_height
        rect = slide.shapes.add_shape(
            1, left, top, width, height
        )
        rect.fill.solid()
        rect.fill.fore_color.rgb = RGBColor(26, 31, 44) # Dark Ink background
        rect.line.fill.background()

        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = paper_title
        title.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
        title.text_frame.paragraphs[0].font.bold = True

        subtitle.text = "Generated by ReproAgent · AI Research Assistant"
        subtitle.text_frame.paragraphs[0].font.color.rgb = RGBColor(139, 92, 246) # Accent Violet
        
        # 2. Description Slide
        desc_slide_layout = prs.slide_layouts[1]
        slide2 = prs.slides.add_slide(desc_slide_layout)
        slide2.shapes.title.text = "Overview"
        slide2.placeholders[1].text = paper_desc

        # 3. Bullet Points Slide
        bullet_slide_layout = prs.slide_layouts[1]
        slide3 = prs.slides.add_slide(bullet_slide_layout)
        
        shapes = slide3.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = "Key Contributions & Findings"
        tf = body_shape.text_frame
        tf.clear()
        
        for bullet in bullets[:7]:
            p = tf.add_paragraph()
            p.text = bullet
            p.level = 0
            p.font.size = Pt(18)
            
        ppt_path = tmp_dir / f"{uuid.uuid4()}.pptx"
        prs.save(str(ppt_path))
        
        return {
            "description": paper_desc + "\n\n" + "\n".join(f"• {b}" for b in bullets),
            "ppt_url": f"/api/download/{ppt_path.name}"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        # Clean up PDF (keep PPT for download)
        if pdf_path.exists():
            pdf_path.unlink()

@app.get("/api/download/{filename}")
async def download_file(filename: str):
    file_path = Path("data/tmp") / filename
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(path=file_path, filename="Paper_Summary.pptx", media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation")

from typing import Optional
from app import run_paper_reproduction

@app.post("/api/run-agent")
async def start_agent_run(
    file: Optional[UploadFile] = File(None),
    url: Optional[str] = Form(None),
    mode: str = Form("Medium"),
    execMode: str = Form("Simulation"),
    maxSteps: int = Form(30)
):
    """Start a ReproAgent run and return a task ID for SSE."""
    task_id = str(uuid.uuid4())
    
    pdf_path = None
    if file:
        tmp_dir = Path("data/tmp")
        tmp_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = tmp_dir / f"{task_id}.pdf"
        with open(pdf_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        
    ACTIVE_TASKS[task_id] = {
        "status": "running",
        "pdf_path": str(pdf_path) if pdf_path else None,
        "url": url or "",
        "mode": mode, # Medium or Hard
        "execMode": execMode,
        "maxSteps": maxSteps,
        "logs": [],
        "state": {},
        "metrics": {},
        "done": False
    }
    
    asyncio.create_task(run_reproagent_task(task_id))
    return {"task_id": task_id}

async def run_reproagent_task(task_id: str):
    task = ACTIVE_TASKS[task_id]
    
    def run_generator():
        # We use the exact logic from app.py
        # but override difficulty based on mode (Medium/Hard)
        # Note: run_paper_reproduction hardcodes "easy" internally, but it works.
        # To perfectly match app.py we just run it.
        gen = run_paper_reproduction(
            pdf_file=task["pdf_path"],
            paper_url=task["url"],
            use_llm=True,
            max_steps=task["maxSteps"],
            execution_mode=task["execMode"],
            clone_dir=f"/tmp/reproagent_{task_id}"
        )
        for result in gen:
            log_md, paper_info_md, metrics_md, state_json = result
            # log_md contains the FULL log string accumulated, so we split it by newlines to get the array
            task["logs"] = log_md.split("\n")
            try:
                task["metrics"] = json.loads(metrics_md)
            except: pass
            try:
                task["state"] = json.loads(state_json)
            except: pass

    try:
        # Run the synchronous generator in a thread to avoid blocking event loop
        await asyncio.to_thread(run_generator)
        task["done"] = True
        task["status"] = "completed"
    except Exception as e:
        task["logs"].append(f"Error: {str(e)}")
        task["done"] = True
        task["status"] = "failed"


@app.get("/api/medium-mode/logs/{task_id}")
async def stream_logs(task_id: str):
    if task_id not in ACTIVE_TASKS:
        raise HTTPException(status_code=404, detail="Task not found")
        
    async def event_generator() -> AsyncGenerator[str, None]:
        task = ACTIVE_TASKS[task_id]
        last_idx = 0
        while not task["done"]:
            if len(task["logs"]) > last_idx:
                new_logs = task["logs"][last_idx:]
                last_idx = len(task["logs"])
                
                data = {
                    "logs": new_logs,
                    "metrics": task.get("metrics", {}),
                    "done": False
                }
                yield f"data: {json.dumps(data)}\n\n"
            await asyncio.sleep(1)
            
        # Send final update
        if len(task["logs"]) > last_idx:
            new_logs = task["logs"][last_idx:]
        else:
            new_logs = []
            
        data = {
            "logs": new_logs,
            "metrics": task.get("metrics", {}),
            "state": task.get("state", {}),
            "done": True,
            "status": task["status"]
        }
        yield f"data: {json.dumps(data)}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="localhost", port=7860, reload=True)
